project: 
  type: website
  output-dir: book

book: 
  title: "Text Analysis NER, Geoparising, and Mapping points with Python"
  author: "Diane López"
  description: "This project shows how to extract places from a body of text and then map locations as points"
format: 
  html: 
    theme: flatly


