---
project: 
  type: website
  output-dir: book

book: 
  title: "Text Analysis NER, Geoparising, and Mapping points with Python"
  author: "Diane López"
  description: "This project shows how to extract places from a body of text and then map locations as points"
  chapters: 
      - index.md
      - 01-Web Scraping.ipynb
      - 02-Text-File-List-to-json.ipynb
      - 03-NER-Spacy-Custome-NER-Model.ipynb
      - 04-Mapping-El-Corrido-de-GregorioCortez_VariantX.ipynb

format: 
  html: 
    theme: flatly
---


